### ISSUE TITLE
Arima parameters

### ISSUE THREAD

**Issue by mpquast** [business-science/modeltime#13]
Hi there! First, I must say I´m loving modeltime! Really great workflow for forecasting! I have one question (kind of more philosophical) and one suggestion (if it makes sense).
1. When trainning with _auto.arima_, I get a model ARIMA(1,23), for example. Then, when refitting, these parameters may change. Wouldn´t it make more sense to keep the same parameters (in my example, 1,2,3), and recalculate just the coefficients? My rationale is that those are the _parameters_ selected during trainning, the same way you select the best number of trees when using xgboost (and keep this number when refitting).
2. As for my suggestion, in my team, we have found that it is interesting to fit multiple ARIMA models using different lengths of the time series as train set, and select the best length. Using modeltime, I can easily do that with _time_series_split_, but, when refitting the model, the whole series is used. It would be interesting that _modeltime_refit_ could use the same length of the time series that was used during trainning (or maybe it is already possible, and I just can´t see how - I apologise if that´s the case).

Thanks!

**Comment by mdancho84** [comment]
Hey @mpquast 

Thanks for reaching out. I'm excited to hear you are loving `modeltime`. 

## Auto ARIMA Refitting

Regarding the Auto ARIMA fitting & refitting with parameters - I would love to include an option to refit with the same model. But, that's actually not how the `forecast::auto.arima()` is set up. It's also probably best to use the model it selects after refitting on the full data set, since this is usually going to perform better. 

Here's the issue: When you select a parameter in `arima_reg(nonseasonal_ar = 2)` , this `nonseasonal_ar` parameter gets mapped to `auto.arima(pmax)`, which is a maximum value. Then when you fit, `auto.arima` cycles through lags up to pmax for the AR term. So it's not a guarantee you'll get a P=2 model. 

Also, Prophet has the same issues. It's an automated model so the parameters are internally selected (e.g. cutpoints). This can and will adapt to the time series, which means refitting results in a different set of points. 

### Proposed Solution - set_engine("arima")

You can always add a second model using `arima_reg()` with `set_engine("Arima")`. Then specify the model you want using `arima_reg()` parameters `nonseasonal_ar`, `nonseasonal_difference`, etc. This will guarantee that you control the model you get.

**Comment by mdancho84** [comment]
## Refit with Shorter Window - Solution

Regarding the second comment, you and your team would like to `modeltime_refit()` with a shorter span than the full data. 

This is relatively straightforward. 

Just select the date range`, then pass to `modeltime_refit(data)`. You'll then refit on a smaller time-frame. 

![image](https://user-images.githubusercontent.com/13734662/88464465-eae56e00-ce88-11ea-8b9a-42fa8b065bda.png)

**Comment by mpquast** [comment]
Thanks a lot for your remarks, Matt! Regarding the shorter span for refitting, as I understand, if I´m working with a model table, and refitting those models with modeltime_refit, the argument "data" will be the same to all models, since it is a tibble, rigth? So, it wouldn´t be possible to have models with different spans on the same table. Not a big problem, really, just trying to understand better.

**Comment by mdancho84** [comment]
OK, I misunderstood. 

When using `modeltime_refit()`, will the `modeltime_table()` will be refit using the same data for all models? Yes - This is how I set it up. If you want to vary the refitting data, I recommend just saving multiple results from `modeltime_refit()`.

**Comment by mdancho84** [comment]
Marking this as completed - I have a more descriptive method for displaying model parameters that get updated after refitting. 

![image](https://user-images.githubusercontent.com/13734662/91251524-a5d38680-e729-11ea-8b72-145173d6a9a4.png)
