### ISSUE TITLE
How to properly refit recursive models?

### ISSUE THREAD

**Issue by kransom14** [business-science/modeltime#186]
I've been trying out some recursive models, but I can't find any examples that show how to use refitting to all data after training on training data with a train and test split. Since the `recursive` function takes the tail of the training data when creating the models, how can I pass the appropriate tail when refitting on all the data? Below is what I have so far, modifying one of the examples from [here](https://business-science.github.io/modeltime/articles/recursive-forecasting.html#make-a-recursive-forecast-model). I'm also curious why I get a warning about rank-deficient fit when forecasting from a calibrated time table, but not when forecasting from the non-calibrated time table like in the original example.

```
library(modeltime)
library(tidymodels)
library(tidyverse)
library(lubridate)
library(timetk)

m750

m750 %>% 
  plot_time_series(
    .date_var    = date, 
    .value       = value, 
    .facet_var   = id, 
    .smooth      = F, 
    .interactive = F
  )

FORECAST_HORIZON <- 24

m750_extended <- m750 %>%
  group_by(id) %>%
  future_frame(
    .length_out = FORECAST_HORIZON,
    .bind_data  = TRUE
  ) %>%
  ungroup()

lag_roll_transformer <- function(data){
  data %>%
    tk_augment_lags(value, .lags = 1:FORECAST_HORIZON) %>%
    tk_augment_slidify(
      contains("lag12"),
      .f = ~mean(.x, na.rm = T),
      .period  = 12,
      .partial = TRUE
    ) 
}

m750_rolling <- m750_extended %>%
  lag_roll_transformer() %>%
  select(-id)

m750_rolling

obs_data <- m750_rolling %>%
  drop_na()

obs_data

# create training and testing splits
splits <- time_series_split(
  data = obs_data,
  assess = 24, 
  cumulative = TRUE)

splits %>% 
  tk_time_series_cv_plan() %>% 
  plot_time_series_cv_plan(date, value)

splits

future_data <- m750_rolling %>%
  filter(is.na(value))

future_data

model_fit_lm <- linear_reg() %>%
  set_engine("lm") %>%
  fit(value ~ date, data = training(splits))

model_fit_lm

# Autoregressive Forecast
model_fit_lm_recursive <- linear_reg() %>%
  set_engine("lm") %>%
  fit(value ~ ., data = training(splits)) %>%
  # One additional step - use recursive()
  recursive(
    transform  = lag_roll_transformer,
    train_tail = tail(training(splits), FORECAST_HORIZON)
  )

model_fit_lm_recursive

model_tbl <- modeltime_table(
  model_fit_lm,
  model_fit_lm_recursive
) 

model_tbl

# calibrate the model time table
calib_tbl <- model_tbl %>% 
  modeltime_calibrate(testing(splits), quiet = FALSE) # calibrating the time table creates testing data predictions in nested tables

# accuracy of model
accuracy_tbl <- calib_tbl %>% 
  modeltime_accuracy(acc_by_id = FALSE)

accuracy_tbl

calib_tbl %>% 
  
  # Forecast testing data
  modeltime_forecast(
    new_data    = testing(splits),
    actual_data = obs_data
  ) %>%
  
  # Visualize the forecast
  plot_modeltime_forecast(
    .interactive        = FALSE,
    .conf_interval_show = FALSE
  )

# refit models on all data
refit_tbl <- calib_tbl %>% 
  modeltime_refit(
    data = obs_data
  ) 

# make predictions on all data
f <- refit_tbl %>% 
  
  # Forecast using future data           
  modeltime_forecast(                    
    new_data    = future_data,                   
    actual_data = obs_data               
  )

f %>%  
  # Visualize the forecast
  plot_modeltime_forecast(
    .interactive        = FALSE,
    .conf_interval_show = FALSE
  )
```

**Comment by AlbertoAlmuinha** [comment]
Hey, 

The tail is fetched based on what was stored in the model/workflow definition and a new recursive definition is simply generated again based on the first one. On the other hand, in both cases the rank-defficient warning appears and it is because variables that are highly correlated (lags) are being used, but it is not an error.

If you want to better understand how predictions are obtained recursively, you can read the documentation of the function (if you haven't already done so) and maybe this article will help you too: https://business-science.github.io/modeltime/articles/recursive-forecasting.html#make-a-recursive-forecast-model

You can also subscribe to the Learning Labs PRO where these topics are covered in more depth: https://university.business-science.io/p/learning-labs-pro

Regards,

**Comment by mdancho84** [comment]
**Rank Deficient Matrix** - This comes from the linear regression because the number of post-processed features is large causing the number of columns to exceed the number of rows in the data. This can lead to overfitting, and the easiest solution is to switch to a model like "glmnet" and add a penalty to features that don't help much. This reduces the rank and addresses the potential overfitting concern. 

**Recursive Forecasting** - I agree with @AlbertoAlmuinha 
 - Free documentation: https://business-science.github.io/modeltime/articles/recursive-forecasting.html
 - Learning Labs PRO has 10 advanced labs on forecasting where I dive deep into concepts like recursive forecasting, iterative forecasting, forecasting when covid events happen, and many other topics.
