### ISSUE TITLE
modeltime_calibrate() fail | Error: Problem occurred getting predictors from new data.

### ISSUE THREAD

**Issue by wallyjulian** [business-science/modeltime#51]
The function modeltime_calibrate() will sometimes fail following an upgrade to the modeltime package or an upgrade to the R version. In this case the fitted model object argument should be refitted before applying modeltime_calibrate().

**Comment by mdancho84** [comment]
## Problem

The models fail return NA or NULL models. This usually happens when the underlying models become incompatable with upgraded software (e.g. using an new version of parsnip or xgboost to predict with models that were trained with older versions).

## Solution

The solution is to use `modeltime_refit()` to refit the models to the data. This revives the old models by retraining them using the newer software (e.g. newer version of parsnip or xgboost that is installed on your computer).
