### ISSUE TITLE
Is tuning parameters with recursive forecasting possible?

### ISSUE THREAD

**Issue by tonyk7440** [business-science/modeltime#60]
Hi All, I've been doing some forecasting using modeltime but have ran into some scaling issues when extending out the horizon as features such as lags < horizon cannot then be used and a new model is needed.
I've seen the enhancement with recursive forecasting which solves this but I'm wondering if it is possible to tune parameters though `tune_grid` and use the recursive forecasting together?

**Comment by mdancho84** [comment]
Circling back on this. The Short Answer - No.

## The Long Answer

We've been tuning the algorithms without recursive because we have access to the lags. Is this perfect - No. But the way we set up `recursive()` is to modify the fitted model. 

I'll need to investigate whether or not we can apply recursive internally to `fit_resamples()` and `tune_grid()` (and friends). It may be possible to incorporate into the process if we can access the fitted models that are created during this process, ,but this will take some investigation. 

So for now, I recommend tuning the models with the lags that are already available in the testing sets, and eventually we can assess whether or not adding recursive to the training process is possible.

**Comment by mdancho84** [comment]
Closing this issue.
