### ISSUE TITLE
GAMs - mgcv modeltime integration

### ISSUE THREAD

**Issue by mdancho84** [business-science/modeltime#71]
Looking for helpers in developing a package related to `modeltime.gam`. May not need to be a new package but `modeltime` is getting quite large. 

References:
- [Noam Ross Tutorials & GAM References](https://github.com/noamross/gam-resources)
- [Modelling seasonal data with GAMs](https://fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/)
- [Extrapolating with B splines and GAMs](https://fromthebottomoftheheap.net/2020/06/03/extrapolating-with-gams/)

**Comment by mdancho84** [comment]
# Challenges

- How will `parsnip` / `workflows` handle the `s()` function. 


# Time Series GAM Example

A quick example of `mgcv::gam()` on time series data.

``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-34. For overview type 'help("mgcv-package")'.
library(modeltime)
library(tidymodels)
library(tidyverse)
library(timetk)
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following objects are masked from 'package:base':
#> 
#>     date, intersect, setdiff, union

m750
#> # A tibble: 306 x 3
#>    id    date       value
#>    <fct> <date>     <dbl>
#>  1 M750  1990-01-01  6370
#>  2 M750  1990-02-01  6430
#>  3 M750  1990-03-01  6520
#>  4 M750  1990-04-01  6580
#>  5 M750  1990-05-01  6620
#>  6 M750  1990-06-01  6690
#>  7 M750  1990-07-01  6000
#>  8 M750  1990-08-01  5450
#>  9 M750  1990-09-01  6480
#> 10 M750  1990-10-01  6820
#> # … with 296 more rows

m750 %>%
    plot_time_series(date, value, .facet_vars = id)
```

![](https://i.imgur.com/bZkzoSp.png)

``` r

data_prepared_tbl <- m750 %>%
    mutate(
        date_month = month(date),
        date_num   = as.numeric(date),
        lag_24     = lag(value, 24)
    ) 

splits <- time_series_split(data_prepared_tbl, assess = "2 years", cumulative = TRUE)
#> Using date_var: date

training(splits)
#> # A tibble: 282 x 6
#>    id    date       value date_month date_num lag_24
#>    <fct> <date>     <dbl>      <dbl>    <dbl>  <dbl>
#>  1 M750  1990-01-01  6370          1     7305     NA
#>  2 M750  1990-02-01  6430          2     7336     NA
#>  3 M750  1990-03-01  6520          3     7364     NA
#>  4 M750  1990-04-01  6580          4     7395     NA
#>  5 M750  1990-05-01  6620          5     7425     NA
#>  6 M750  1990-06-01  6690          6     7456     NA
#>  7 M750  1990-07-01  6000          7     7486     NA
#>  8 M750  1990-08-01  5450          8     7517     NA
#>  9 M750  1990-09-01  6480          9     7548     NA
#> 10 M750  1990-10-01  6820         10     7578     NA
#> # … with 272 more rows
testing(splits)
#> # A tibble: 24 x 6
#>    id    date       value date_month date_num lag_24
#>    <fct> <date>     <dbl>      <dbl>    <dbl>  <dbl>
#>  1 M750  2013-07-01  9030          7    15887   8800
#>  2 M750  2013-08-01  9620          8    15918   9360
#>  3 M750  2013-09-01 10050          9    15949   9650
#>  4 M750  2013-10-01 10610         10    15979  10280
#>  5 M750  2013-11-01 10760         11    16010  10410
#>  6 M750  2013-12-01 10570         12    16040  10240
#>  7 M750  2014-01-01 10730          1    16071  10380
#>  8 M750  2014-02-01 10660          2    16102  10390
#>  9 M750  2014-03-01 10900          3    16130  10580
#> 10 M750  2014-04-01 11020          4    16161  10560
#> # … with 14 more rows

model_fit_gam <- gam(
    formula = value ~ s(date_month, bs = "cc", k = 12) + s(date_num) + s(lag_24), 
    data    = training(splits)
)
model_fit_gam
#> 
#> Family: gaussian 
#> Link function: identity 
#> 
#> Formula:
#> value ~ s(date_month, bs = "cc", k = 12) + s(date_num) + s(lag_24)
#> 
#> Estimated degrees of freedom:
#> 9.30 8.59 4.53  total = 23.42 
#> 
#> GCV score: 43686.42

preds_train <- predict(model_fit_gam, newdata = training(splits)) %>% as.numeric()
preds_test  <- predict(model_fit_gam, newdata = testing(splits)) %>% as.numeric()

bind_rows(
    training(splits),
    testing(splits) %>% add_column(predictions = preds_test)
) %>%
    select(id, date, value, predictions) %>%
    pivot_longer(
        cols = c(value, predictions),
        names_to  = "name",
        values_to = "value"
    ) %>%
    mutate(name = as_factor(name)) %>%
    plot_time_series(
        date, value, .color_var = name, .smooth = F
    )
```

![](https://i.imgur.com/XDgl5Yh.png)

<sup>Created on 2021-03-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by mdancho84** [comment]
Adding this comment for posterity:

> What I like about GAMs also is that they are very different to a tree-based approach, e.g. RF, XGB so should be great in an ensemble.  And unlike linear regression, as with GLMs, you can assume different distributions for the errors, not just gaussian, but also binomial, poisson and gamma.  For errors, read "outcomes", i.e. different distributions for the outputs...  Since time series are often non-negative in nature, such as financial price series, the symmetrical assumption of gaussian/normal errors is not appropriate.
In my work, we've used GLM/GAMs a bit for insurance pricing, and it's common to model the frequency / counts of claims using a poisson error distribution, and the severity / size of claims using a gamma error distribution, which is bit like a lognormal distribution.  You also transform predictions to a log scale using a "link" function.
Logistic regression is really just a GLM with a binomial error distribution plus a "squashing function" to convert predictions to a probability, i.e. on a [0,1] scale.  Called a logistic link function, the one you also see in neural nets.  But a GLM is restricted to linear, monotonic relationships.  If you want to model non-linearity, e.g. a U-shape relationship between age and insurance risk, say, or indeed any real world phenomena, then Logistic GAMs, and GAMs in general with other error distributions such as Poisson, Gamma, etc,,, take things up a level.
GAMs = "GLMS on steroids", you might say!  Maybe you knew most of this already, but if not, then it's nice to return the favour once since I've learned so much from you!

**Comment by AlbertoAlmuinha** [comment]
Hi @mdancho84 ,

I have tried creating this model to see how it affected the s() function and have not encountered any problems at least using the "formula" parsnip interface. I attach a proof of concept where the results can be seen.

Regards,

![proof_of_concept](https://user-images.githubusercontent.com/34541991/111847128-863fbd80-8908-11eb-8718-a0f84e80f7bf.PNG)

**Comment by mdancho84** [comment]
Very nice!! 👍

**Comment by BenWynne-Morris** [comment]
Awesome Alberto!  Thanks for working this.
Note - if you replace a smooth s() with a tensor ti() for the interaction you might get a better performance...  
While s() is good for variables on the same scale, e.g. geospatial (x, y) coordinates, ti() has an additional smoothing parameter, which helps when the variables involved in the interaction have different scales.
It is also recommended by experts like Noam Ross to use method = "REML" instead of method = "GCV" in the gam() fitting.

**Comment by AlbertoAlmuinha** [comment]
Hi @BenWynne-Morris ,

If you want to replace smooth s() with a tensor ti(), it is enough to modify the formula in parsnip::fit() and add in ti() the parameters you want. You can also change the method to use through parsnip::set_engine (and all the parameters of mgcv::gam) as I show in the attached image.

Greetings,

PS: Are you working on this? To be honest I just did this function out of curiosity to see how it affected the s() issue. I don't know what the modeling idea is but if you want me to help you with this for me no problem.

![params](https://user-images.githubusercontent.com/34541991/111850830-9f00a100-8911-11eb-93f0-3441a4e3501f.PNG)

**Comment by mdancho84** [comment]
This looks great. What's everyone's thoughts? I'm thinking either:
1. A new R package called `modeltime.gam` that covers just what we need for regression, or 
2. Alternatively, we could be a little more ambitious and make a `gamsnip` R package. This would cover regression, classification, and multi-class, and be useful for a broader problem set of business beyond just forecasting.

**Comment by AlbertoAlmuinha** [comment]
Hi,

IMHO, the first option doesn't convince me because I think it could risk accumulating too many packages in the modeltime ecosystem (in that case, wouldn't it be better to include it directly in modeltime together with the rest of the algorithms?) I can understand package size issues but I think an additional package would be reserved for something more general. I think too many overly specific packages can make people not really know what packages are at the end (but this is just my opinion).

So maybe the `gamsnip` option is the best. But whatever you say :)

**Comment by BenWynne-Morris** [comment]
No strong opinion.

**Comment by mdancho84** [comment]
OK, I'm leaning towards a new R package that covers GAM models and the `mgcv` package. We OK with `gamsnip`? If so, I'll create a repo for it.

**Comment by AlbertoAlmuinha** [comment]
I’m OK ✅✅

Let’s go with gamsnip

**Comment by mdancho84** [comment]
Alright. I will set up tomorrow.

**Comment by BenWynne-Morris** [comment]
Hi @AlbertoAlmuinha, 

For an interactive intro to the theory, you might find this reference helpful:
https://m-clark.github.io/generalized-additive-models/case_for_gam.html

I recently took the course provided by Noam Ross (https://noamross.github.io/gams-in-r-course/), which is really amazing.

I'm relatively new to GAMs and package development but will follow along and try and help out where I can, e.g. testing, etc.  If you have any questions about GAMs, I'll attempt to fill in the gaps.  Note that once you have fitted a gam model object, you can use `summary()`, `plot()` and `predict()` just like with a fitted `lm` model object.  The `broom` package functions such as `tidy()`, `glance()` and `augment()` also work with fitted GAM objects.

Very basic theory:
**GLMs are a generalisation of linear regression**, with two key differences: 
(1) errors don't have to be normally distributed, e.g. you could have binomial / poisson / gamma errors instead 
(2) linear predictions can be transformed using another function

Linear regression uses (1) gaussian errors (2) an "identity" transformation function
Logistic Regression is also a special case of a GLM with (1) binomial errors (2) a squashing function to transform predictions to a [0,1] range, so they can be interpreted as probabilities.

**GAMs are a generalisation of GLMs**.  The `s()` function wrapped around a variable name means that the algorithm has the flexibility to find a non-linear relationship (e.g. U-shape or montonic relationship) instead of a linear relationship between predictors and the target.  With two variables inside the `s()`, you're specifying a 2-d smooth interaction.  It's like adding an interaction in linear regression, but with GAMs you can have a surface instead of a plane.

The following graph is an example of how the thing we're predicting varies with a 2-d smooth, with confidence intervals added to show the uncertainty of the estimated 2-d smooth surface:
![image](https://user-images.githubusercontent.com/52631826/111866607-9ab2a300-8966-11eb-9a8c-f3f678508082.png)

**Comment by mdancho84** [comment]
Hey @AlbertoAlmuinha and @BenWynne-Morris I've moved this project to business-science/gamsnip#1

**Comment by AlbertoAlmuinha** [comment]
Thank you very much @BenWynne-Morris for the explanation. I found really useful the first link and for sure I will take the Datacamp course.

**Comment by AlbertoAlmuinha** [comment]
Can we close this issue too?

**Comment by mdancho84** [comment]
Yes, covered in parsnip now.
